/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_siperia_peopleinphotos_expression */

#include <vector>
#include <string>

#ifndef _Included_com_siperia_peopleinphotos_expression
#define _Included_com_siperia_peopleinphotos_expression
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_siperia_peopleinphotos_expression
 * Method:    nativeCreateObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_siperia_peopleinphotos_expression_nativeCreateObject
  (JNIEnv *, jclass);

/*
 * Class:     com_siperia_peopleinphotos_expression
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_siperia_peopleinphotos_expression
 * Method:    nativeSetFilterSize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeSetFilterSize
  (JNIEnv *, jclass, jlong, jint, jint);

JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeELBP
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jfloat);

JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeARLBP
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint);

JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeSkinThreshold
  (JNIEnv *, jclass, jlong, jlong, jlong, jboolean);

JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeLocalMeanThreshold
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jfloat);

JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeConcatHist
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);


JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeInitModels
(JNIEnv *, jclass, jlong, jint, jdouble, jint, jdouble, jboolean );

JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeAddFisherface
(JNIEnv *, jclass, jlong, jlong, jint );

JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeTrainFisherfaces
(JNIEnv *, jclass, jlong );

JNIEXPORT jint JNICALL Java_com_siperia_peopleinphotos_expression_nativePredictFisherface
(JNIEnv *, jclass, jlong, jlong );

JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeAddEigenface
(JNIEnv *, jclass, jlong, jlong, jint );

JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeEdgeHistogram
  (JNIEnv *, jclass, jlong, jlong, jlong);

JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeTrainEigenfaces
(JNIEnv *, jclass, jlong );

JNIEXPORT jint JNICALL Java_com_siperia_peopleinphotos_expression_nativePredictEigenface
(JNIEnv *, jclass, jlong, jlong );

JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeGaborLBPHistograms
(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint );

JNIEXPORT void JNICALL Java_com_siperia_peopleinphotos_expression_nativeGetEigenPictures
(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
